# Generated by Django 3.1.6 on 2022-06-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
