# Generated by Django 3.1.6 on 2022-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Type', 'Type'), ('Covid-19 Test', 'Covid-19 Test'), ('Covid-19 Vaccination', 'Covid-19 Vaccination')], default='Type', max_length=50)),
                ('Patientname', models.CharField(max_length=20)),
                ('Contactno', models.CharField(max_length=10)),
                ('Appointmentdate', models.DateField()),
                ('Time', models.TimeField(default='HH:MM')),
                ('Aadharno', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Rejected', 'Rejected'), ('Waiting for covid test', 'Waiting for covid test'), ('Waitinglist for vaccine', 'Waiting list for vaccine'), ('Covid-19 vaccined Dose 1', 'Covid-19 vaccined Dose 1'), ('Covid-19 vaccined Dose 2', 'Covid-19 vaccined Dose 2'), ('Covid-19 +ve', 'Covid-19 +ve'), ('Covid-19 -ve', 'Covid-19 -ve'), ('Others', 'Others')], default='Pending', max_length=50)),
                ('notes', models.CharField(max_length=50)),
                ('appointmentcreateuser', models.CharField(max_length=50)),
                ('loggeduser', models.CharField(max_length=50)),
            ],
        ),
    ]
