# Generated by Django 3.1.6 on 2022-06-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentcreateuser',
        ),
    ]
